router_id = "1.1.1.1"       # Default Router ID for the service
default_as = 65000
poll_interval = 5


[[peers]]
remote_ip = "127.0.0.2"
enabled = true
dest_port = 1179
remote_as = 65001
hold_timer = 30
families = [
    "ipv6 unicast",
]
passive = true